### ISSUE TITLE
Requesting headshot photos

### ISSUE THREAD

**Issue by frances-chen** [HoustonGwG/Houston_GwG#7]
Hey everyone,

I'm creating vector sketches of everyone for the homepage. I need headshot photos of everyone to work off of.

So far, I've received photos from: Erica, Lou, Yara, Richard, and Ross.

Thanks!

**Comment by Omena234** [comment]
![omena](https://user-images.githubusercontent.com/34484646/38170131-6a803ede-3542-11e8-896a-dd1647965a79.jpg)
